[build]
  base = "."                # Because we're already inside /client
  publish = "dist"          # Output folder of Vite
  command = "npm run build"

[functions]
  directory = "../netlify"  # Path from /client to /netlify
